apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "ipapp.labels" . | nindent 4 }}
  name: svc-{{ include "ipapp.fullname" . }}
spec:
  ports:
  - port: {{ .Values.envs.FLASK_PORT }}
    protocol: TCP
    targetPort: {{ .Values.envs.FLASK_PORT }}
  selector:
    {{- include "ipapp.selectorLabels" . | nindent 4 }}
  type: NodePort
