---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "ipapp.labels" . | nindent 4 }}
  name: svc-{{ include "ipapp.fullname" . }}
spec:
  ports:
  - port: {{ .Values.envs.FLASK_PORT }}
    protocol: TCP
    targetPort: {{ .Values.envs.FLASK_PORT }}
  selector:
    {{- include "ipapp.selectorLabels" . | nindent 4 }}
  type: NodePort

---
apiVersion: networking.k8s.io/v1
kind: ingress-{{ include "ipapp.fullname" . }}
metadata:
  name: ingress-ipapp
  annotations:
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/healthcheck-path: "{{ .Values.service.healthcheckPath }}"
    alb.ingress.kubernetes.io/load-balancer-name: "{{ include "ipapp.fullname" . }}"
    alb.ingress.kubernetes.io/subnets: "{{ .Values.service.subnets }}"
spec:
  ingressClassName: alb
  rules:
    - http:
        paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: svc-{{ include "ipapp.fullname" . }}
              port:
                number: {{ .Values.envs.FLASK_PORT }}
